export type DescriptionUnitItem = {
  id: string;
  title: string;
  summary: string;
  bullets: string[];
  codePath: string;
  renderable: boolean;
  usedInPrototype: boolean;
};

export const componentUnitItems: DescriptionUnitItem[] = [
  {
    id: 'component.button',
    title: 'Button',
    summary: '사용자 액션 트리거를 담당하는 기본 클릭 컴포넌트',
    bullets: ['Primary/Secondary 역할 분리', '로딩/비활성 상태 정책 필요'],
    codePath: 'src/blocks/molecules/ListHeader.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.select',
    title: 'Select',
    summary: '단일 값 선택형 입력 컴포넌트',
    bullets: ['기본값(default) 명시', '선택 옵션 개수가 많으면 검색형 확장 고려'],
    codePath: 'src/blocks/molecules/ListSortSelect.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.input',
    title: 'Input',
    summary: '텍스트 검색/입력용 기본 필드',
    bullets: ['placeholder와 aria-label 제공', '입력 즉시 반영 vs 제출 반영 정책 명시'],
    codePath: 'src/blocks/molecules/ListSearchInput.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.chip',
    title: 'Chip',
    summary: '짧은 필터 상태 또는 태그를 나타내는 토큰형 UI',
    bullets: ['선택/미선택 상태 구분', '다중 선택 시 wrap 정책 필요'],
    codePath: 'src/blocks/molecules/ListFilterChips.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.toggle',
    title: 'Toggle',
    summary: '두 가지 상태(List/Grid 등)를 빠르게 전환',
    bullets: ['현재 활성 상태 강조', '토글 결과가 즉시 렌더에 반영'],
    codePath: 'src/blocks/molecules/ViewModeToggle.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.card.project',
    title: 'Card - Project',
    summary: '프로젝트 목록에서 사용하는 대표 카드 컴포넌트',
    bullets: ['썸네일 + 제목 + 역할 배지 + 설명 구조', '카드 클릭 시 상세 화면 진입 흐름에 최적화'],
    codePath: 'src/blocks/organisms/ProjectCard.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.card.library',
    title: 'Card - Library Asset',
    summary: '라이브러리 목록에서 사용하는 에셋 카드 컴포넌트',
    bullets: ['출력명/출처/메타 정보를 밀도 있게 표시', 'Grid/List 전환 및 설명 하이라이트 연동 지원'],
    codePath: 'src/blocks/organisms/LibraryAssetCard.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
];

export const blockUnitItems: DescriptionUnitItem[] = [
  {
    id: 'desc-rfm.globalTopNav',
    title: '전역 상단 네비게이션 (GlobalTopNavBlock)',
    summary: '브랜드, 메뉴, 유틸 버튼, 액션 아이콘을 포함하는 공통 상단 블록',
    bullets: ['Home/Projects/Library 공통 사용', '우측 아이콘 액션과 utility button 확장 지원'],
    codePath: 'src/blocks/molecules/GlobalTopNav.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.listHeader',
    title: '타이틀 영역 (ListHeaderBlock)',
    summary: '화면 제목/설명과 주요 액션 버튼을 묶는 상단 블록',
    bullets: ['화면 목적을 한 줄로 이해 가능해야 함', '액션 버튼은 선택적으로 노출'],
    codePath: 'src/blocks/molecules/ListHeader.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.sectionTitle',
    title: '세미 타이틀 (SectionTitleBlock)',
    summary: '콘텐츠 섹션의 소제목과 카운트 칩을 함께 표시하는 보조 헤더 블록',
    bullets: ['테이블/리스트 상단의 문맥 구분', '카운트 칩은 실제 데이터 개수와 동기화'],
    codePath: 'src/blocks/molecules/SectionTitle.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.listToolbar',
    title: '검색 영역 (ListToolbarBlock)',
    summary: '검색, 필터, 정렬, 보조 컨트롤을 한 줄로 구성하는 조작 블록',
    bullets: ['검색 입력 즉시 반영 정책 권장', 'rightExtras 슬롯으로 화면별 확장'],
    codePath: 'src/blocks/organisms/ListToolbar.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.dataTable',
    title: '데이터 테이블 (DataTableBlock)',
    summary: '열 기반의 데이터셋/리스트 정보를 표 형태로 표현하는 블록',
    bullets: ['컬럼 정렬(left/center/right) 지원', 'Source 칩, Action 버튼 등 커스텀 셀 지원'],
    codePath: 'src/blocks/organisms/DataTable.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.tablePagination',
    title: '테이블 페이지네이션 (TablePaginationBlock)',
    summary: '테이블 하단의 페이지 이동과 현재 범위 정보를 제공하는 블록',
    bullets: ['Prev/Next 탐색 지원', '현재 페이지 범위(start-end) 표시'],
    codePath: 'src/blocks/molecules/TablePagination.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.libraryAssetGrid',
    title: '카드 리스트 (LibraryAssetGridBlock)',
    summary: '결과 데이터를 카드 컬렉션으로 배치/표시하는 콘텐츠 블록',
    bullets: ['Grid/List 보기 전환 대응', '카드 내부 title/source/meta 규칙 준수'],
    codePath: 'src/blocks/organisms/LibraryAssetGrid.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectWorkspaceSidebar',
    title: '프로젝트 좌측 사이드바 (ProjectWorkspaceSidebarBlock)',
    summary: '프로젝트 컨텍스트 메뉴와 사용자 영역을 포함한 좌측 내비게이션 블록',
    bullets: ['Dashboard/Workspace/Settings 메뉴', '프로젝트 타이틀 드롭다운형 헤더 포함'],
    codePath: 'src/blocks/organisms/ProjectWorkspaceSidebar.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectMetaInfoStrip',
    title: '프로젝트 메타 정보 띠 (ProjectMetaInfoStripBlock)',
    summary: 'Task/Robot/Started Date/Owner 정보를 한 줄로 요약하는 메타 블록',
    bullets: ['프로젝트 타이틀 하단 배치', '짧은 라벨+값 조합 반복 구조'],
    codePath: 'src/blocks/molecules/ProjectMetaInfoStrip.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectWorkspaceActivityCards',
    title: '워크스페이스 액티비티 카드 (ProjectWorkspaceActivityCardsBlock)',
    summary: 'Register/Collect/Generate/Curate 등 작업 진입 버튼 카드 그룹 블록',
    bullets: ['카드 전체 클릭형 진입 버튼', '도메인 탭에 따라 카드셋 교체 가능'],
    codePath: 'src/blocks/organisms/ProjectWorkspaceActivityCards.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.workPageTemplateCanvas',
    title: '워크페이지 템플릿 캔버스 (WorkPageTemplateCanvasBlock)',
    summary: 'WorkPage 화면 유형(Type1~Type4 변형)을 스켈레톤 레이아웃으로 제공하는 템플릿 블록',
    bullets: ['총 6개 레이아웃 변형 제공', '실제 업무 컨텐츠 삽입 전 구조 표준화 용도'],
    codePath: 'src/blocks/organisms/WorkPageTemplateCanvas.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.workPageShell',
    title: '워크페이지 풀사이즈 셸 (WorkPageShellBlock)',
    summary: '헤더/스텝바/컨텐츠 영역을 포함한 full-size popup work page 공통 셸',
    bullets: ['우측 History 버튼 제공', '각 work 버튼 클릭 시 템플릿 변형과 함께 오픈'],
    codePath: 'src/blocks/organisms/WorkPageShell.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectTaskList',
    title: '할당 작업 리스트 (ProjectTaskListBlock)',
    summary: '담당 작업 목록과 실행 액션 버튼을 제공하는 작업 보드 블록',
    bullets: ['작업명/태그/설명/기한/우선순위 포함', '카드 단위 Run 액션 제공'],
    codePath: 'src/blocks/organisms/ProjectTaskList.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectInfoListPanel',
    title: '정보 리스트 패널 (ProjectInfoListPanelBlock)',
    summary: 'Recent Activity/Member와 같은 세로 리스트 섹션에 재사용하는 블록',
    bullets: ['타이틀/서브타이틀/메타/배지 지원', '컴팩트 카드 리스트 구조'],
    codePath: 'src/blocks/organisms/ProjectInfoListPanel.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectRobotInfoPanel',
    title: '로봇 정보 패널 (ProjectRobotInfoPanelBlock)',
    summary: '로봇 이미지와 기본 스펙 텍스트를 요약 노출하는 정보 블록',
    bullets: ['좌측 썸네일, 우측 설명 텍스트', '프로젝트 하단 요약 섹션 배치'],
    codePath: 'src/blocks/organisms/ProjectRobotInfoPanel.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectOutputSummaryPanel',
    title: '산출물 요약 패널 (ProjectOutputSummaryPanelBlock)',
    summary: 'Dataset/Model 산출물 수치를 카드 형태로 요약하는 블록',
    bullets: ['수치 중심 강조', '증감 텍스트 보조 노출'],
    codePath: 'src/blocks/organisms/ProjectOutputSummaryPanel.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectSelectorCard',
    title: '프로젝트 선택 카드 (ProjectSelectorCardBlock)',
    summary: '프로젝트 전환 패널에서 hover/select 상태를 갖는 카드 블록',
    bullets: ['프로젝트 요약 정보와 이미지 영역 표시', '선택 상태에서 강조 테두리 적용'],
    codePath: 'src/blocks/organisms/ProjectSelectorCard.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
];

export const overlayUnitItems: DescriptionUnitItem[] = [
  {
    id: 'desc-rfm.overlayDialog',
    title: '중앙 모달 오버레이 (OverlayDialogBlock)',
    summary: '중앙 팝업 패널을 제공하는 공통 모달 블록',
    bullets: ['ESC/닫기 버튼 처리', '알림/설정/선택 플로우 공통 사용'],
    codePath: 'src/blocks/molecules/OverlayDialog.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.screenDescriptionPanel',
    title: '우측 설명 패널 (ScreenDescriptionPanelBlock)',
    summary: '화면 단위 설명을 우측에서 제공하는 공통 드로워 블록',
    bullets: ['Description 버튼과 연동', 'Hover 시 화면 하이라이트 흐름 지원'],
    codePath: 'src/blocks/organisms/ScreenDescriptionPanel.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectSelectorPanel',
    title: '프로젝트 전환 패널 (ProjectSelectorPanelBlock)',
    summary: '중앙 모달 형태로 프로젝트 검색/선택/생성을 제공하는 프로젝트 스위처',
    bullets: ['상단 Search + New Project 버튼', '카드 선택 후 Select 버튼으로 최종 프로젝트 전환'],
    codePath: 'src/blocks/organisms/ProjectSelectorPanel.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.workspaceItemDetailDrawer',
    title: '워크스페이스 항목 상세 드로워 (WorkspaceItemDetailDrawerBlock)',
    summary: '워크스페이스 테이블 항목 클릭 시 우측에서 상세 정보를 보여주는 드로워',
    bullets: ['Overview/Task Details 탭 구성', 'Task Details 내 통계 카드 + 테이블 + 페이지네이션 제공'],
    codePath: 'src/blocks/organisms/WorkspaceItemDetailDrawer.block.tsx',
    renderable: true,
    usedInPrototype: false,
  },
  {
    id: 'desc-rfm.projectJobsOnProcessDrawer',
    title: '작업 진행 드로워 (ProjectJobsOnProcessDrawerBlock)',
    summary: 'Workspace 타이틀 우측 Jobs on process 버튼으로 여는 우측 오버레이 드로워',
    bullets: ['Search + Source filter 제공', '작업 카드(작업명/설명/Source/작업자/진행률) 리스트 제공'],
    codePath: 'src/blocks/organisms/ProjectJobsOnProcessDrawer.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
];

export const screenPatternUnitItems: DescriptionUnitItem[] = [
  {
    id: 'page.dashboard',
    title: 'Dashboard',
    summary: '위젯 기반으로 핵심 지표와 최근 항목을 한 화면에 배치하는 개요형 화면',
    bullets: ['대표 경로: /home', '요약 카드 + 섹션형 위젯(리스트/피드) 조합 구조'],
    codePath: 'src/screens/home/HomeDashboard/HomeDashboard.screen.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'page.list',
    title: 'List',
    summary: '탐색/검색/필터 중심의 목록형 화면',
    bullets: ['대표 경로: /library, /projects', '상단 조작 영역 + 리스트 영역 기본 구조'],
    codePath: 'src/patterns/list-base/ListBase.pattern.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'page.detail',
    title: 'Project Detail Dashboard',
    summary: '좌측 사이드바 + 우측 작업/정보 위젯으로 구성된 프로젝트 상세 대시보드 화면 패턴',
    bullets: ['대표 경로: /projects/:projectId', '작업/활동/리소스 섹션을 한 화면에서 운영'],
    codePath: 'src/screens/projects/ProjectDetail/ProjectDetail.screen.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'page.workspace',
    title: 'Project Workspace',
    summary: '프로젝트 데이터 작업 액티비티 진입과 데이터셋 목록 운영을 위한 워크스페이스 화면 패턴',
    bullets: ['대표 경로: /projects/:projectId/workspace', '도메인 탭 + 활동 진입 카드 + 데이터 테이블 조합'],
    codePath: 'src/screens/projects/ProjectWorkspace/ProjectWorkspace.screen.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'page.work',
    title: 'Work Page',
    summary: '각 work 활동 버튼을 통해 열리는 full-size popup 실행 화면 패턴',
    bullets: ['대표 진입: Workspace 내 activity card 클릭', '공통 헤더 + 스텝바 + 템플릿 캔버스 구조'],
    codePath: 'src/blocks/organisms/WorkPageShell.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'page.form',
    title: 'Form',
    summary: '생성/수정 입력을 위한 폼형 화면',
    bullets: ['입력 검증/오류 메시지 정책 필수', '저장/취소 액션 명확히 분리'],
    codePath: 'src/pages/auth/Login/Login.page.tsx',
    renderable: true,
    usedInPrototype: true,
  },
];
