export type DescriptionUnitItem = {
  id: string;
  title: string;
  summary: string;
  bullets: string[];
  codePath: string;
  renderable: boolean;
  usedInPrototype: boolean;
};

export const componentUnitItems: DescriptionUnitItem[] = [
  {
    id: 'component.toast',
    title: 'Toast (notification)',
    summary: '고정 하단 중앙 피드백 — 5초 후 자동 소거(호버 시 일시정지)·닫기 버튼, workspace 저장 완료 등에 사용',
    bullets: ['role=status, aria-live=polite', 'autoHideMs 기본 5s, 호버 중 타이머 정지', 'CloseOutlined 닫기'],
    codePath: 'src/blocks/molecules/Toast.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.button',
    title: 'Button (variants)',
    summary: '액션 트리거 — 크기(md/sm)·역할(Primary/Secondary/Danger)·테이블 행·모달 전폭 등은 buttonClasses 단일 소스',
    bullets: [
      'md: h-9 Primary/Secondary/Destructive, sm: h-8, 테이블 행: h-6, 모달 전폭: h-11',
      '아이콘만: buttonIconGhostClasses',
      '신규 변형은 buttonClasses.ts + ButtonCatalogShowcase에 추가',
    ],
    codePath: 'src/blocks/molecules/Button.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.select',
    title: 'Select (native)',
    summary:
      '단일 값 선택 — 네이티브 select 시각은 formFieldClasses.formControlSelectClasses 단일 소스. 문서·기획에서 Dropdown이라 부르는 네이티브 선택도 동일 유닛',
    bullets: [
      '기본값(default) 명시',
      '블록 예: ListSortSelectBlock — 화면별로 formControlSelectClasses(및 min-w 등)만 조합',
      '옵션이 매우 많으면 검색형 셀렉트를 별도 블록으로 추가 후 카탈로그에만 한 줄 등록',
    ],
    codePath: 'src/blocks/molecules/ListSortSelect.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.input',
    title: 'Input',
    summary: '텍스트 입력 — formFieldClasses(formControlInputClasses 등)로 블록·카탈로그와 동일 토큰',
    bullets: ['placeholder·aria-label', '즉시 반영 vs 제출 반영 정책은 화면별로 명시'],
    codePath: 'src/blocks/molecules/ListSearchInput.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.textarea',
    title: 'Textarea',
    summary: '여러 줄 입력 — formControlTextareaClasses',
    bullets: ['높이는 화면·블록에서 rows 또는 min-h로 지정', '리사이즈 정책은 블록별로 명시'],
    codePath: 'src/blocks/styles/formFieldClasses.ts',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.chip',
    title: 'Chip (variants)',
    summary: '필터·폼 태그·메타 배지 등 용도별 크기를 구분한 칩 계열 — 스타일은 chipClasses + Chip.block',
    bullets: [
      'Filter · md: 리스트 툴바 (h-8)',
      '컴팩트 sm: Source·역할·메타·배지는 h-6 + text-[11px] (chipClasses)',
      'Tag · xs: 폼 태그 + 제거 (RemovableTagChip)',
      '블록에 새 칩이 필요하면 chipClasses에 규격 추가 후 Catalog 미리보기 반영',
    ],
    codePath: 'src/blocks/molecules/Chip.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.toggle',
    title: 'Toggle',
    summary: '두 가지 상태(List/Grid 등)를 빠르게 전환',
    bullets: ['현재 활성 상태 강조', '토글 결과가 즉시 렌더에 반영'],
    codePath: 'src/blocks/molecules/ViewModeToggle.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.tabs',
    title: 'Tabs',
    summary: '세그먼트 전환 — 리스트용 underline(ListStatusTabs)과 드로어용 패딩 탭(tabClasses) 구분',
    bullets: [
      'tabClasses: tabUnderline* (목록), tabDrawer* (우측 패널)',
      '블록: ListStatusTabsBlock',
    ],
    codePath: 'src/blocks/molecules/TabsShowcase.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.card.project',
    title: 'Card - Project',
    summary: '프로젝트 목록에서 사용하는 대표 카드 컴포넌트',
    bullets: ['썸네일 + 제목 + 역할 배지 + 설명 구조', '카드 클릭 시 상세 화면 진입 흐름에 최적화'],
    codePath: 'src/blocks/organisms/ProjectCard.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'component.card.library',
    title: 'Card - Library Asset',
    summary: '라이브러리 목록에서 사용하는 에셋 카드 컴포넌트',
    bullets: [
      '전체 클릭형(button), hover·선택(selected) 상태',
      'Dataset/Model 상세 경로로 이동 시 목록 복귀 선택 유지(state)',
    ],
    codePath: 'src/blocks/organisms/LibraryAssetCard.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
];

export const blockUnitItems: DescriptionUnitItem[] = [
  {
    id: 'desc-rfm.globalTopNav',
    title: '전역 상단 네비게이션 (GlobalTopNavBlock)',
    summary: '브랜드, 메뉴, 유틸 버튼, 액션 아이콘을 포함하는 공통 상단 블록',
    bullets: [
      '구성: 내비 링크·아이콘 버튼·브랜드 (컴포넌트 버튼/링크 토큰과 정렬)',
      'Home/Projects/Library 공통 사용',
      '우측: 임시 utility 버튼(Capture screen → Description → Logout) + 아이콘 액션 — `createTemporaryTopUtilityButtons`',
      'Settings 아이콘: 넓은 오버레이 + GlobalNavSettingsPanelBlock(LNB·검색·General/Theme/RFM 등 섹션)',
    ],
    codePath: 'src/blocks/molecules/GlobalTopNav.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.globalNavSettingsPanel',
    title: 'GNB 설정 패널 (GlobalNavSettingsPanelBlock)',
    summary:
      '설정 오버레이 본문 — 상단 사용자 정보, 검색으로 섹션 필터, 좌측 메뉴 클릭 시 우측에 General·Theme·RFM·데이터·로보틱스·파이프라인 알림 패널',
    bullets: [
      '프로토타입 폼·더미 값; i18n gnb.settings.*',
      'GNB Settings 액션에서만 합성(단독 카탈로그 프리뷰 없음)',
    ],
    codePath: 'src/blocks/organisms/GlobalNavSettingsPanel.block.tsx',
    renderable: false,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.listHeader',
    title: '타이틀 영역 (ListHeaderBlock)',
    summary: '화면 제목/설명과 주요 액션 버튼을 묶는 상단 블록',
    bullets: ['구성: component.button', '화면 목적을 한 줄로 이해 가능해야 함', '액션 버튼은 선택적으로 노출'],
    codePath: 'src/blocks/molecules/ListHeader.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.robotSelectCard',
    title: '로봇 선택 카드 (RobotSelectCardBlock)',
    summary: 'Create Project 로봇 피커용 카드 — hover 시 스펙 면, 선택 시 링 강조',
    bullets: ['앞면: 이름 + 썸네일 플레이스홀더', '뒷면: RFM / Fine-tuning / Dataset 수(더미)'],
    codePath: 'src/blocks/molecules/RobotSelectCard.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.editProfilePanel',
    title: '프로필 편집 패널 (EditProfilePanelBlock)',
    summary: 'Edit Profile 팝업 본문 — 표시명·프로필 사진·프로젝트 역할 배지; 비 Owner 시 data/model engineer 신청',
    bullets: [
      'user-role-policy Dev 서브 역할(project owner / data engineer / model engineer) 배지',
      'project owner가 아니면 Request additional Dev access 섹션',
    ],
    codePath: 'src/blocks/organisms/EditProfilePanel.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.inviteMemberPanel',
    title: '멤버 초대 패널 (InviteMemberPanelBlock)',
    summary: 'Invite members 모달 본문 — 이메일·이름 검색 후 사용자 선택, 역할 부여, 초대 전송',
    bullets: [
      '검색 입력 + Search 버튼으로 디렉터리 필터(프로토타입 더미)',
      '멤버 테이블과 동일한 Role 옵션(Project owner / Data engineer 등)',
      '사용자 미선택 시 Send invite 비활성',
    ],
    codePath: 'src/blocks/organisms/InviteMemberPanel.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.sectionTitle',
    title: '세미 타이틀 (SectionTitleBlock)',
    summary: '콘텐츠 섹션의 소제목과 카운트 칩을 함께 표시하는 보조 헤더 블록',
    bullets: [
      '구성: component.chip (Meta · xs, chipMetaCountClasses)',
      '테이블/리스트 상단의 문맥 구분',
      '카운트 칩은 실제 데이터 개수와 동기화',
    ],
    codePath: 'src/blocks/molecules/SectionTitle.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.listToolbar',
    title: '검색 영역 (ListToolbarBlock)',
    summary: '검색, 필터, 정렬, 보조 컨트롤을 한 줄로 구성하는 조작 블록',
    bullets: [
      '구성: component.input(ListSearchInput), component.chip(Filter·md), component.select(ListSortSelect)',
      '검색 입력 즉시 반영 정책 권장',
      'rightExtras 슬롯으로 화면별 확장',
    ],
    codePath: 'src/blocks/organisms/ListToolbar.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.listStatusTabs',
    title: '상태 탭 (ListStatusTabsBlock)',
    summary: '목록 상단 상태 필터 — tabUnderline* 토큰, list-base·워크스페이스·설정에서 사용',
    bullets: ['구성: component.tabs(tabClasses underline)', '활성 탭은 하단 보더 강조'],
    codePath: 'src/blocks/molecules/ListStatusTabs.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.dataTable',
    title: '데이터 테이블 (DataTableBlock)',
    summary: '열 기반의 데이터셋/리스트 정보를 표 형태로 표현하는 블록',
    bullets: [
      '구성: 셀 렌더러에서 component.chip·component.button 등 카탈로그 단위 재사용',
      '컬럼 정렬(left/center/right) 지원',
      'Source 칩, Action 버튼 등 커스텀 셀 지원',
    ],
    codePath: 'src/blocks/organisms/DataTable.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.tablePagination',
    title: '테이블 페이지네이션 (TablePaginationBlock)',
    summary: '테이블 하단의 페이지 이동과 현재 범위 정보를 제공하는 블록',
    bullets: [
      '구성: component.button(이동)·component.select(페이지 크기)',
      'Prev/Next 탐색 지원',
      '현재 페이지 범위(start-end) 표시',
    ],
    codePath: 'src/blocks/molecules/TablePagination.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.libraryAssetGrid',
    title: '카드 리스트 (LibraryAssetGridBlock)',
    summary: '결과 데이터를 카드 컬렉션으로 배치/표시하는 콘텐츠 블록',
    bullets: [
      '구성: component.card.library(LibraryAssetCardBlock)',
      'Grid/List 보기 전환 대응',
      '선택된 asset id·onSelect 콜백으로 상세 라우팅 연동',
    ],
    codePath: 'src/blocks/organisms/LibraryAssetGrid.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectWorkspaceSidebar',
    title: '프로젝트 좌측 사이드바 (ProjectWorkspaceSidebarBlock)',
    summary: '프로젝트 컨텍스트 메뉴와 사용자 영역을 포함한 좌측 내비게이션 블록',
    bullets: ['Dashboard/Workspace/Settings 메뉴', '프로젝트 타이틀 드롭다운형 헤더 포함'],
    codePath: 'src/blocks/organisms/ProjectWorkspaceSidebar.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectMetaInfoStrip',
    title: '프로젝트 메타 정보 띠 (ProjectMetaInfoStripBlock)',
    summary: 'Task/Robot/Started Date/Owner 정보를 한 줄로 요약하는 메타 블록',
    bullets: ['프로젝트 타이틀 하단 배치', '짧은 라벨+값 조합 반복 구조'],
    codePath: 'src/blocks/molecules/ProjectMetaInfoStrip.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectWorkspaceActivityCards',
    title: '워크스페이스 액티비티 카드 (ProjectWorkspaceActivityCardsBlock)',
    summary: 'Register/Collect/Generate/Curate 등 작업 진입 버튼 카드 그룹 블록',
    bullets: [
      '카드 전체 클릭형 진입 버튼',
      'Generate 등은 activityMenus로 팝오버 옵션 후 진입 가능',
      '도메인 탭에 따라 카드셋 교체 가능',
    ],
    codePath: 'src/blocks/organisms/ProjectWorkspaceActivityCards.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.formTagInput',
    title: '폼 태그 입력 (FormTagInputBlock)',
    summary: '엔터로 태그를 추가하고, 칩 우측 X로 제거하는 파라미터 영역용 태그 필드',
    bullets: [
      '구성: component.input, component.chip(Tag·xs, RemovableTagChip)',
      '인풋은 formFieldClasses 단일 소스',
      '태그 칩은 인풋 아래 배치 · 대소문자 무시 중복 방지',
    ],
    codePath: 'src/blocks/molecules/FormTagInput.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.workPageFormField',
    title: '워크페이지 폼 필드 (WorkPageFormFieldBlock)',
    summary:
      'Register / Collect / Generate step-1 네이티브 인풋 라벨 단일 소스 — workPageFormFieldLabelOuter/Inner 토큰과 동일 타이포',
    bullets: [
      'WorkPageFormFieldBlock: label+required+children; WorkPageFormFieldLabelText: 토글·복합 필드용 라벨 행',
      'formFieldClasses의 workPageFormFieldLabelOuterClasses·workPageFormFieldStackClasses와 함께 사용',
    ],
    codePath: 'src/blocks/molecules/WorkPageFormField.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.workPageFileUploadDropzone',
    title: '워크페이지 파일 업로드 드롭존 (WorkPageFileUploadDropzoneBlock)',
    summary:
      'Register 우측 카드 머리글·인풋 라벨은 `toTitleCase` 규칙(File Settings 등); File Upload 드롭존은 동일 타이포',
    bullets: [
      'Register(WorkPageTemplateCanvas type2) 및 Synthetic Video Creation 좌측에서 공통 사용',
      '선택 파일명 표시 시 File Upload로 교체·Clear로 onFileChange(null)',
      'Synthetic 좌열은 ActivityStepContainer: 스크롤 본문 + flex footer에 Run/Rerun',
    ],
    codePath: 'src/blocks/molecules/WorkPageFileUploadDropzone.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.activityStepContainer',
    title: '액티비티 스텝 컨테이너 (ActivityStepContainerBlock)',
    summary:
      '헤더(타이틀) + flex-1 overflow-y-auto 본문 + 선택적 푸터 — 카드 높이를 채우며 버튼은 푸터에만 두고 sticky/absolute 없음',
    bullets: [
      '스타일 토큰: activityStepContainerClasses, activityStepHeaderClasses, activityStepContentClasses, activityStepFooterClasses',
      'Collect / Generate / Register type2 / Curate 등 activity step-1 카드 공통 껍데기',
    ],
    codePath: 'src/blocks/molecules/ActivityStepContainer.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.workPageActivityFooterToolbar',
    title: '워크페이지 액티비티 푸터 툴바 (WorkPageActivityFooterToolbarBlock)',
    summary:
      'ActivityStepContainer 푸터 안에서만 쓰는 좌·우 버튼 행 — workPageActivityFooterToolbarRowClasses (sticky 아님)',
    bullets: [
      'Register type2 우측(File settings) Previous/Register, Collect·Generate·Curate step-1 등',
      '예전 WorkPageActivityStickyToolbarBlock 대체 — 위치는 항상 카드 하단 flex 푸터',
    ],
    codePath: 'src/blocks/molecules/WorkPageActivityFooterToolbar.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.workPageTemplateCanvas',
    title: '워크페이지 템플릿 캔버스 (WorkPageTemplateCanvasBlock)',
    summary: 'WorkPage 화면 유형(Type1~Type4 변형)을 스켈레톤 레이아웃으로 제공하는 템플릿 블록',
    bullets: [
      '구성: desc-rfm.workPageFormField, desc-rfm.workPageFileUploadDropzone, desc-rfm.activityStepContainer, desc-rfm.workPageActivityFooterToolbar, desc-rfm.formTagInput, component.input·select·textarea 등',
      'type2-parameter-only(Register): 우측 File settings 카드는 ActivityStepContainer + 푸터에 Previous·Register(desc-rfm.workPageActivityFooterToolbar)',
      '총 6개 레이아웃 변형 제공',
      '실제 업무 컨텐츠 삽입 전 구조 표준화 용도',
    ],
    codePath: 'src/blocks/organisms/WorkPageTemplateCanvas.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.activityValidation',
    title: '액티비티 프리프로세서 단계 (ActivityValidationBlock)',
    summary:
      '여러 Activity에서 공통으로 쓰는 Pre-processor 스텝: 요약 카드, 진행 바(종료 시 동일 폭 액션 스트립으로 전환), 테이블·비디오 프리뷰. `preprocessorRecordCount`: Register 20건, Collect 5건 등 비율(success≈10:warn≈5:fail≈5) 유지',
    bullets: [
      'Register → Pre-processor → Save 플로의 2단계',
      'n/N·Total Records는 `preprocessorRecordCount`와 동일(워크스페이스에서 activity별 전달)',
      '완료 후 Delete Selected / Delete Failed / Re-run pre-processor',
      '하단: Skip은 프리프로세서 없이 Save dataset 단계로 이동, Save results는 전처리 완료 후',
      '하단 primary: Save results → Save 단계로 이동 시 셸 본문 스크롤 상단 정렬',
    ],
    codePath: 'src/blocks/organisms/ActivityValidation.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.activitySaveDataset',
    title: '액티비티 저장 단계 (ActivitySaveDatasetBlock)',
    summary:
      '워크플로 3단계 — Pre-processor와 동일한 `rounded-xl` 셸; Register step1과 동일 `workPageCanvasCardClasses`·2열 그리드; 요약 지표는 Pre-processor 카드와 동일 시각 언어',
    bullets: [
      '좌열 카드: Dataset name / Description / 도메인 태그',
      '우열 카드: Output summary(지표 4칸 + 메타 dl), Modalities, contains, Export',
      '푸터: `workPageStep1FooterRowClasses` — Previous / Save dataset',
      'mock 요약 수치는 activity별 `getActivitySaveSummary` — Register는 Pre-processor 행 수(20)와 합산 일치',
    ],
    codePath: 'src/blocks/organisms/ActivitySaveDataset.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.collectTeleoperationStep',
    title: 'Collect 텔레옵 스텝 (CollectTeleoperationStepBlock)',
    summary:
      'Collect activity 1단계(Teleoperation) — ActivityStepContainer 푸터에 WorkPageActivityFooterToolbar(좌: Apply / 우: Start…Finish+Save)',
    bullets: [
      '버튼 의미는 docs/policies/collect-teleoperation-actions.md 단일 소스',
      '세션 제어·Save는 우측 카드 flex 푸터(스크롤 본문과 분리, sticky 없음)',
      '에피소드 진행률 바는 녹화 경과 초 / 에피소드당 최대 초(프로토 20s); Next로 채우지 않음',
      'Save는 Finish 또는 해당 에피소드 녹화 종료(최대 도달·Stop) 시 활성',
      '카메라: 좌·중·우 가로 비율(중앙 넓게 16∶9), 프로토타입은 연결 토글만',
    ],
    codePath: 'src/blocks/organisms/CollectTeleoperationStep.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.syntheticVideoCreationStep',
    title: 'Generate 합성 영상 스텝 (SyntheticVideoCreationStepBlock)',
    summary:
      'Generate activity 1단계 — ActivityStepContainer: 좌 푸터 Run/Rerun, 우 complete 시 푸터 Save',
    bullets: [
      'Collect step 1과 동일한 2열 그리드·높이 토큰(workPageStep1TwoColumnGridClasses, collectTeleopGridHeightClasses)',
      '워크플로 스테퍼 1단계 라벨: Synthetic Video Generation(해당 generateMode일 때)',
      'File Upload 영역은 Register type2와 동일 molecule(WorkPageFileUploadDropzoneBlock), 파라미터와 한 카드에 병합',
      '영상 완료 후 컨트롤은 본문 흐름 레이아웃(오버레이·backdrop-blur 없음)',
    ],
    codePath: 'src/blocks/organisms/SyntheticVideoCreationStep.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.mimicAugmentationStep',
    title: 'Generate Mimic Augmentation 스텝 (MimicAugmentationStepBlock)',
    summary:
      'Generate activity 1단계(mimic-augmentation) — ActivityStepContainer: 좌 푸터 Run/Rerun, 우 complete 시 푸터 Save',
    bullets: [
      'Synthetic Video와 동일 2열 그리드·높이 토큰(workPageStep1TwoColumnGridClasses, collectTeleopGridHeightClasses)',
      '워크플로 스테퍼 1단계 라벨: Mimic Augmentation(generateMode=mimic-augmentation)',
      '우측 머리글 WORK_PAGE_SIMULATION_PREVIEW_TITLE; 스크롤 본문 progress·썸네일, Save는 푸터',
    ],
    codePath: 'src/blocks/organisms/MimicAugmentationStep.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.idmTrajectoryStep',
    title: 'Generate IDM trajectory 스텝 (IdmTrajectoryStepBlock)',
    summary:
      'Generate activity 1단계(generateMode=idm) — 좌 푸터 Run fusion, 우 푸터 Continue; 프리뷰는 본문 그라데이션 박스(absolute 레이어 없음)',
    bullets: [
      'Mimic/Synthetic와 동일 2열 그리드·높이 토큰',
      '워크스페이스 Saved Datasets에서 클립 옵션 주입 가능(datasetClips)',
      'Run fusion·Continue는 각 열 ActivityStepContainer 푸터',
    ],
    codePath: 'src/blocks/organisms/IdmTrajectoryStep.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.mergeDatasetsStep',
    title: 'Curate Merge datasets 스텝 (MergeDatasetsStepBlock)',
    summary:
      'Curate 1단계(merge-datasets) — 상·하 두 ActivityStepContainer: 선택+preview 스크롤 / merged output 이름·설명+푸터 Continue',
    bullets: [
      'Data Foundry Saved Datasets와 동일 Source 칩(chipSourceActivityClasses)',
      '워크플로 스테퍼: merge datasets / pre-processor / save datasets',
      'merged output: 푸터에 Continue to pre-processor',
    ],
    codePath: 'src/blocks/organisms/MergeDatasetsStep.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.curateAnalyticsStep',
    title: 'Curate Analytics 스텝 (CurateAnalyticsStepBlock)',
    summary: 'Curate 1단계(analytics) — ActivityStepContainer + 푸터 Continue + 자리 표시형 패널; 후속 차트·필터 UI 연결 예정',
    bullets: ['URL curateMode=analytics', 'Continue는 카드 flex 푸터'],
    codePath: 'src/blocks/organisms/CurateAnalyticsStep.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.workPageShell',
    title: '워크페이지 풀사이즈 셸 (WorkPageShellBlock)',
    summary: '헤더/스텝바/컨텐츠 영역을 포함한 full-size work page 공통 셸',
    bullets: [
      '우측 Save draft → 현재 세션 스냅샷을 드로어 목록 맨 위에 추가 후 Load draft 오픈; Load draft → 같은 activity의 draft만 드로워에 표시(?overlay=activity-draft-history)',
      '3단계 스텝퍼: 잠긴 미래 단계는 비활성, 이전 단계는 자유 이동',
      'activity 경로 전환(/workspace/:workKey) 시 워크플로 단계 리셋',
    ],
    codePath: 'src/blocks/organisms/WorkPageShell.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectTaskList',
    title: '할당 작업 리스트 (ProjectTaskListBlock)',
    summary: '담당 작업 목록과 실행 액션 버튼을 제공하는 작업 보드 블록',
    bullets: ['작업명/태그/설명/기한/우선순위 포함', '카드 단위 Run 액션 제공'],
    codePath: 'src/blocks/organisms/ProjectTaskList.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectInfoListPanel',
    title: '정보 리스트 패널 (ProjectInfoListPanelBlock)',
    summary: 'Recent Activity/Member 등 세로 리스트 — `member` 옵션 시 아바타·역할 칩( user-role-policy )',
    bullets: [
      '구성: 기본 행은 타이틀·서브타이틀·메타·배지',
      'member: { avatarUrl, roles } 시 프로필 사진(또는 이니셜) + Dev 역할 칩',
      '역할 칩 스타일은 Edit Profile과 memberRolePresentation 공유',
    ],
    codePath: 'src/blocks/organisms/ProjectInfoListPanel.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectRobotInfoPanel',
    title: '로봇 정보 패널 (ProjectRobotInfoPanelBlock)',
    summary: '로봇 이미지와 기본 스펙 텍스트를 요약 노출하는 정보 블록',
    bullets: ['좌측 썸네일, 우측 설명 텍스트', '프로젝트 하단 요약 섹션 배치'],
    codePath: 'src/blocks/organisms/ProjectRobotInfoPanel.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectOutputSummaryPanel',
    title: '산출물 요약 패널 (ProjectOutputSummaryPanelBlock)',
    summary: 'Dataset/Model 산출물 수치를 카드 형태로 요약하는 블록',
    bullets: ['수치 중심 강조', '증감 텍스트 보조 노출'],
    codePath: 'src/blocks/organisms/ProjectOutputSummaryPanel.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectSelectorCard',
    title: '프로젝트 선택 카드 (ProjectSelectorCardBlock)',
    summary: '프로젝트 전환 패널에서 hover/select 상태를 갖는 카드 블록',
    bullets: ['프로젝트 요약 정보와 이미지 영역 표시', '선택 상태에서 강조 테두리 적용'],
    codePath: 'src/blocks/organisms/ProjectSelectorCard.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
];

export const overlayUnitItems: DescriptionUnitItem[] = [
  {
    id: 'desc-rfm.overlayDialog',
    title: '중앙 모달 오버레이 (OverlayDialogBlock)',
    summary: '중앙 팝업 패널을 제공하는 공통 모달 블록',
    bullets: [
      '구성: 헤더·본문·component.button(닫기/확인 등) 패턴',
      'ESC/닫기 버튼 처리',
      '알림/설정/선택 플로우 공통 사용',
    ],
    codePath: 'src/blocks/molecules/OverlayDialog.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.screenDescriptionPanel',
    title: '우측 설명 패널 (ScreenDescriptionPanelBlock)',
    summary: '화면 단위 설명을 우측에서 제공하는 공통 드로워 블록',
    bullets: ['Description 버튼과 연동', 'Hover 시 화면 하이라이트 흐름 지원'],
    codePath: 'src/blocks/organisms/ScreenDescriptionPanel.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.projectSelectorPanel',
    title: '프로젝트 전환 패널 (ProjectSelectorPanelBlock)',
    summary: '중앙 모달 형태로 프로젝트 검색/선택/생성을 제공하는 프로젝트 스위처',
    bullets: ['상단 Search + New Project 버튼', '카드 선택 후 Select 버튼으로 최종 프로젝트 전환'],
    codePath: 'src/blocks/organisms/ProjectSelectorPanel.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.workspaceItemDetailDrawer',
    title: '워크스페이스 항목 상세 드로워 (WorkspaceItemDetailDrawerBlock)',
    summary: '워크스페이스 테이블 항목 클릭 시 우측에서 상세 정보를 보여주는 드로워',
    bullets: ['Overview/Task Details 탭 구성', 'Task Details 내 통계 카드 + 테이블 + 페이지네이션 제공'],
    codePath: 'src/blocks/organisms/WorkspaceItemDetailDrawer.block.tsx',
    renderable: true,
    usedInPrototype: false,
  },
  {
    id: 'desc-rfm.projectJobsOnProcessDrawer',
    title: '작업 진행 드로워 (ProjectJobsOnProcessDrawerBlock)',
    summary: 'Workspace 타이틀 우측 Jobs on process 버튼으로 여는 우측 오버레이 드로워',
    bullets: ['Search + Source filter 제공', '작업 카드(작업명/설명/Source/작업자/진행률) 리스트 제공'],
    codePath: 'src/blocks/organisms/ProjectJobsOnProcessDrawer.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'desc-rfm.activityDraftHistoryDrawer',
    title: '액티비티 임시저장 히스토리 드로워 (ActivityDraftHistoryDrawerBlock)',
    summary: 'Work page Load draft 버튼 — 현재 열린 activity와 동일한 activity의 draft만 목록에 표시, 검색·선택·복원 (슬라이드 드로어)',
    bullets: [
      '목록은 현재 activity에 한정 (예: Register 화면에서는 register draft만)',
      '선택 시 해당 activity 경로로 이동 + location.state 복원',
      'RFM 파라미터 요약 노출',
    ],
    codePath: 'src/blocks/organisms/ActivityDraftHistoryDrawer.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
];

export const screenPatternUnitItems: DescriptionUnitItem[] = [
  {
    id: 'page.dashboard',
    title: 'Dashboard',
    summary: '위젯 기반으로 핵심 지표와 최근 항목을 한 화면에 배치하는 개요형 화면',
    bullets: [
      '주요 구성: 화면별 블록·카드 배치(카탈로그 컴포넌트 토큰 정렬)',
      '대표 경로: /home',
      '요약 카드 + 섹션형 위젯(리스트/피드) 조합 구조',
    ],
    codePath: 'src/screens/home/HomeDashboard/HomeDashboard.screen.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'page.list',
    title: 'List',
    summary: '탐색/검색/필터 중심의 목록형 화면',
    bullets: [
      '주요 구성: desc-rfm.globalTopNav, desc-rfm.listHeader, desc-rfm.listToolbar, desc-rfm.dataTable 등 list-base 패턴',
      '대표 경로: /library, /projects',
      '상단 조작 영역 + 리스트 영역 기본 구조',
    ],
    codePath: 'src/patterns/list-base/ListBase.pattern.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'page.createProjectRobot',
    title: 'Create Project — Select Robot',
    summary: 'GNB만 두고 풀뷰포트로 로봇을 고르는 프로젝트 생성 1단계',
    bullets: [
      '주요 구성: desc-rfm.robotSelectCard, desc-rfm.globalTopNav',
      '경로 /projects/new',
      '좌측 프리뷰 + 우측 2x2 RobotSelectCard',
      'Select → /projects/new/details',
    ],
    codePath: 'src/screens/projects/ProjectCreate/ProjectCreate.screen.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'page.detail',
    title: 'Project Detail Dashboard',
    summary: '좌측 사이드바 + 우측 작업/정보 위젯으로 구성된 프로젝트 상세 대시보드 화면 패턴',
    bullets: [
      '주요 구성: desc-rfm.projectWorkspaceSidebar, desc-rfm.projectTaskList, desc-rfm.projectInfoListPanel 등',
      '대표 경로: /projects/:projectId',
      '작업/활동/리소스 섹션을 한 화면에서 운영',
    ],
    codePath: 'src/screens/projects/ProjectDetail/ProjectDetail.screen.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'page.workspace',
    title: 'Project Workspace',
    summary: '프로젝트 데이터 작업 액티비티 진입과 데이터셋 목록 운영을 위한 워크스페이스 화면 패턴',
    bullets: [
      '주요 구성: desc-rfm.listToolbar, desc-rfm.dataTable, desc-rfm.workPageShell, desc-rfm.formTagInput 등',
      '대표 경로: /projects/:projectId/workspace',
      '도메인 탭 + 활동 진입 카드 + 데이터 테이블 조합',
      'Data Foundry / Model Institute 탭: user-role-policy — owner는 둘 다, data engineer는 Data Foundry만, model engineer는 Model Institute만(getWorkspaceTabVisibility)',
    ],
    codePath: 'src/screens/projects/ProjectWorkspace/ProjectWorkspace.screen.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'page.settings',
    title: 'Project Workspace Settings',
    summary: '워크스페이스 설정을 General/Members/Jobs/Resource 탭으로 운영하는 설정 화면 패턴',
    bullets: [
      '주요 구성: desc-rfm.globalTopNav, desc-rfm.dataTable, desc-rfm.projectSelectorPanel 등',
      '대표 경로: /projects/:projectId/workspace/settings',
      '탭 전환 + 테이블/카드 조합 구조',
    ],
    codePath: 'src/screens/projects/ProjectSettings/ProjectSettings.screen.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'page.work',
    title: 'Work Page',
    summary: '각 work 활동 버튼 클릭 후 URL 전환으로 진입하는 full-size 실행 화면 패턴',
    bullets: [
      '주요 구성: desc-rfm.workPageShell, desc-rfm.workPageTemplateCanvas, desc-rfm.collectTeleoperationStep(Collect), desc-rfm.syntheticVideoCreationStep(Generate·synthetic-video), desc-rfm.mimicAugmentationStep(Generate·mimic-augmentation), desc-rfm.idmTrajectoryStep(Generate·idm), desc-rfm.mergeDatasetsStep(Curate·merge-datasets), desc-rfm.curateAnalyticsStep(Curate·analytics), desc-rfm.activityValidation, desc-rfm.activitySaveDataset',
      '대표 경로: /projects/:projectId/workspace/:workKey',
      '공통 헤더 + 스텝바 + (액티비티별) 캔버스 구조',
    ],
    codePath: 'src/blocks/organisms/WorkPageShell.block.tsx',
    renderable: true,
    usedInPrototype: true,
  },
  {
    id: 'page.form',
    title: 'Form',
    summary: '생성/수정 입력을 위한 폼형 화면',
    bullets: [
      '주요 구성: component.input·button(formFieldClasses 토큰)',
      '입력 검증/오류 메시지 정책 필수',
      '저장/취소 액션 명확히 분리',
    ],
    codePath: 'src/pages/auth/Login/Login.page.tsx',
    renderable: true,
    usedInPrototype: true,
  },
];
