export type Domain = 'Common' | 'Dev' | 'Supporter Center' | 'Admin Console' | 'Consumer';
export type RowType = 'Page' | 'Popup' | 'Layer';

export type IaItem = {
  key: string;
  domain: Domain;
  depth1: string;
  depth2?: string;
  depth3?: string;
  depth4?: string;
  depth5?: string;
  screenName: string;
  type: RowType;
  path?: string;
  linkedToKey?: string;
  description?: string;
};

// Editable IA source of truth:
// Update this list and save, then /flow will reflect it.
export const iaItems: IaItem[] = [
  {
    key: 'common-login',
    domain: 'Common',
    depth1: 'Login',
    depth2: 'Sign In',
    screenName: 'Login',
    description: 'IP/PW 로그인 및 역할 선택 진입',
    type: 'Page',
    path: '/',
  },
  {
    key: 'dev-home-dashboard',
    domain: 'Dev',
    depth1: 'Home',
    depth2: 'Dashboard',
    screenName: 'Home Dashboard',
    description: 'Developer 첫 진입 대시보드',
    type: 'Page',
    path: '/home',
  },
  {
    key: 'dev-project-list',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    screenName: 'Project List',
    description: '프로젝트 카드 탐색 및 상세 진입',
    type: 'Page',
    path: '/projects',
  },
  {
    key: 'dev-project-create-robot',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Create',
    depth4: 'Select Robot',
    screenName: 'Create Project — Select Robot',
    description: 'GNB만 노출, 풀뷰포트에서 로봇 선택 후 상세 입력 단계로 진행',
    type: 'Page',
    path: '/projects/new',
    linkedToKey: 'dev-project-list',
  },
  {
    key: 'dev-project-create-details',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Create',
    depth4: 'Project Details',
    screenName: 'Create Project — Details (placeholder)',
    description: '로봇 선택 후 프로젝트 메타 입력(추후 기획)',
    type: 'Page',
    path: '/projects/new/details',
    linkedToKey: 'dev-project-create-robot',
  },
  {
    key: 'dev-project-detail',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Dashboard',
    screenName: 'Project Detail Dashboard',
    description: '프로젝트 단위 작업/활동/멤버/로봇 정보 확인. 헤더 Edit Layout은 쿼리 없이 인라인 popover.',
    type: 'Page',
    path: '/projects/:projectId',
  },
  {
    key: 'dev-workspace-data-foundry',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Workspace',
    depth4: 'Data Foundry',
    screenName: 'Workspace Data Foundry',
    description: 'Data Foundry 액티비티 진입, 데이터셋 운영, Jobs drawer',
    type: 'Page',
    path: '/projects/:projectId/workspace',
  },
  {
    key: 'dev-workspace-model-institute',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Workspace',
    depth4: 'Model Institute',
    screenName: 'Workspace Model Institute',
    description: 'Model Institute 액티비티 진입, 데이터셋 운영, Jobs drawer',
    type: 'Page',
    path: '/projects/:projectId/workspace',
  },
  {
    key: 'dev-work-register',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Workspace',
    depth4: 'Data Foundry',
    depth5: 'Register',
    screenName: 'Work Page Register',
    description: 'Register activity 작업 화면 (스텝 1~3: 등록·검증·저장)',
    type: 'Page',
    path: '/projects/:projectId/workspace/register',
  },
  {
    key: 'dev-work-activity-save-dataset',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Workspace',
    depth4: 'Data Foundry',
    depth5: 'Activity Save',
    screenName: 'Activity Save Dataset (step 3)',
    description: 'Work shell 내 3단계 — 데이터셋명·설명 편집 및 RFM 산출 요약 후 저장 (동일 work 경로, 스텝 전환)',
    type: 'Page',
    path: '/projects/:projectId/workspace/register',
    linkedToKey: 'dev-workspace-data-foundry',
  },
  {
    key: 'dev-work-collector',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Workspace',
    depth4: 'Data Foundry',
    depth5: 'Collector',
    screenName: 'Work Page Collector',
    description: 'Collect activity — 1 Teleoperation / 2 Pre-processor / 3 Save; 텔레옵 파라미터·에피소드·카메라 패널',
    type: 'Page',
    path: '/projects/:projectId/workspace/collector',
  },
  {
    key: 'dev-work-generator',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Workspace',
    depth4: 'Data Foundry',
    depth5: 'Generator',
    screenName: 'Work Page Generator',
    description: 'Generator activity 작업 화면',
    type: 'Page',
    path: '/projects/:projectId/workspace/generator',
  },
  {
    key: 'dev-work-curator',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Workspace',
    depth4: 'Data Foundry',
    depth5: 'Curator',
    screenName: 'Work Page Curator',
    description: 'Curator activity 작업 화면',
    type: 'Page',
    path: '/projects/:projectId/workspace/curator',
  },
  {
    key: 'dev-work-trainer',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Workspace',
    depth4: 'Model Institute',
    depth5: 'Trainer',
    screenName: 'Work Page Trainer',
    description: 'Trainer activity 작업 화면',
    type: 'Page',
    path: '/projects/:projectId/workspace/trainer',
  },
  {
    key: 'dev-work-evaluator',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Workspace',
    depth4: 'Model Institute',
    depth5: 'Evaluator',
    screenName: 'Work Page Evaluator',
    description: 'Evaluator activity 작업 화면',
    type: 'Page',
    path: '/projects/:projectId/workspace/evaluator',
  },
  {
    key: 'dev-settings-general',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Settings',
    depth4: 'General',
    screenName: 'Workspace Settings General',
    description: '워크스페이스 기본 정책/쿼터/환경 설정',
    type: 'Page',
    path: '/projects/:projectId/workspace/settings',
  },
  {
    key: 'dev-settings-members',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Settings',
    depth4: 'Members',
    screenName: 'Workspace Settings Members',
    description: '프로젝트 멤버 목록/권한 상태 관리',
    type: 'Page',
    path: '/projects/:projectId/workspace/settings',
  },
  {
    key: 'dev-settings-jobs',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Settings',
    depth4: 'Jobs',
    screenName: 'Workspace Settings Jobs',
    description: '운영 Job 스케줄/상태 관리',
    type: 'Page',
    path: '/projects/:projectId/workspace/settings',
  },
  {
    key: 'dev-settings-resource',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Settings',
    depth4: 'Resource',
    screenName: 'Workspace Settings Resource',
    description: '리소스 레지스트리 검색/필터/페이지 관리',
    type: 'Page',
    path: '/projects/:projectId/workspace/settings',
  },
  {
    key: 'dev-library-dataset',
    domain: 'Dev',
    depth1: 'Library',
    depth2: 'Dataset',
    screenName: 'Library Dataset',
    description: '게시된 Dataset 탐색 및 상세 정보 확인',
    type: 'Page',
    path: '/library',
  },
  {
    key: 'dev-library-model',
    domain: 'Dev',
    depth1: 'Library',
    depth2: 'Model',
    screenName: 'Library Model',
    description: '게시된 Model 탐색 및 상세 정보 확인',
    type: 'Page',
    path: '/library',
  },
  {
    key: 'dev-library-dataset-detail',
    domain: 'Dev',
    depth1: 'Library',
    depth2: 'Dataset',
    depth3: 'Detail',
    screenName: 'Library Dataset Detail',
    description: 'Dataset 카드 선택 시 메타·더미 상세(프로토타입)',
    type: 'Page',
    path: '/library/datasets/:assetId',
    linkedToKey: 'dev-library-dataset',
  },
  {
    key: 'dev-library-model-detail',
    domain: 'Dev',
    depth1: 'Library',
    depth2: 'Model',
    depth3: 'Detail',
    screenName: 'Library Model Detail',
    description: 'Model 카드 선택 시 메타·더미 상세(프로토타입)',
    type: 'Page',
    path: '/library/models/:assetId',
    linkedToKey: 'dev-library-model',
  },
  {
    key: 'common-login-role-popup',
    domain: 'Common',
    depth1: 'Login',
    depth2: 'Sign In',
    depth3: 'Role Select',
    screenName: 'Role Select Popup',
    description: 'Login 버튼 클릭 시 역할 선택 모달 (Developer/Consumer/Supporter/Admin)',
    type: 'Popup',
    path: '/',
    linkedToKey: 'common-login',
  },
  {
    key: 'dev-project-selector-popup',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Dashboard',
    depth4: 'Project Selector',
    screenName: 'Project Selector Popup',
    description: 'Dashboard LNB 프로젝트 타이틀 클릭 시 프로젝트 전환(쿼리 오버레이). Workspace/Settings에서는 동일 UI를 URL 없이 로컬로 연다.',
    type: 'Popup',
    path: '/projects/:projectId?overlay=project-selector',
    linkedToKey: 'dev-project-detail',
  },
  {
    key: 'dev-edit-profile-popup',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Dashboard',
    depth4: 'Edit Profile',
    screenName: 'Edit Profile Popup',
    description: '표시명·사진·역할 배지 편집; 비 Owner 시 data/model engineer 추가 권한 신청(EditProfilePanelBlock). Dashboard는 ?overlay=edit-profile, Workspace/Settings는 로컬 오버레이.',
    type: 'Popup',
    path: '/projects/:projectId?overlay=edit-profile',
    linkedToKey: 'dev-project-detail',
  },
  {
    key: 'dev-jobs-on-process-drawer',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Workspace',
    depth4: 'Jobs on process',
    screenName: 'Jobs on process Drawer',
    description: 'Workspace 헤더 우측 Jobs on process 버튼 클릭 시 열리는 우측 드로워',
    type: 'Layer',
    path: '/projects/:projectId/workspace?overlay=jobs-on-process',
    linkedToKey: 'dev-workspace-data-foundry',
  },
  {
    key: 'dev-activity-draft-history-drawer',
    domain: 'Dev',
    depth1: 'Project',
    depth2: 'Project List',
    depth3: 'Workspace',
    depth4: 'Load draft',
    screenName: 'Activity draft history Drawer',
    description: 'Work page Load draft 버튼 — 미저장 activity 임시저장 세션 카드 목록(우측 슬라이드)',
    type: 'Layer',
    path: '/projects/:projectId/workspace/:workKey?overlay=activity-draft-history',
    linkedToKey: 'dev-workspace-data-foundry',
  },
  {
    key: 'dev-gnb-notifications-popup',
    domain: 'Common',
    depth1: 'Global Navigation',
    depth2: 'Notifications',
    screenName: 'Notifications Popup',
    description: 'GNB 알림 아이콘 클릭 시 중앙 오버레이 팝업',
    type: 'Popup',
    path: '/projects/:projectId',
    linkedToKey: 'dev-project-detail',
  },
  {
    key: 'dev-gnb-settings-popup',
    domain: 'Common',
    depth1: 'Global Navigation',
    depth2: 'Settings',
    screenName: 'GNB Settings Popup',
    description: 'GNB 설정 아이콘 클릭 시 중앙 오버레이 팝업',
    type: 'Popup',
    path: '/projects/:projectId',
    linkedToKey: 'dev-project-detail',
  },
  {
    key: 'dev-gnb-announcements-popup',
    domain: 'Common',
    depth1: 'Global Navigation',
    depth2: 'Announcements',
    screenName: 'Announcements Popup',
    description: 'GNB 공지 아이콘 클릭 시 중앙 오버레이 팝업',
    type: 'Popup',
    path: '/projects/:projectId',
    linkedToKey: 'dev-project-detail',
  },
];
