export type BlockMeta = {
  id: string;
  version: string;
  owner: string;
  category: 'molecule' | 'organism';
  description: string;
  tags: string[];
};

export const blockRegistry: BlockMeta[] = [
  {
    id: 'rfm.filterBar',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Search and filter controls for list screens',
    tags: ['filter', 'search', 'list'],
  },
  {
    id: 'rfm.dataTable',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Tabular data display block',
    tags: ['table', 'list', 'columns'],
  },
  {
    id: 'rfm.globalTopNav',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Global navigation header',
    tags: ['navigation', 'global', 'header'],
  },
  {
    id: 'rfm.globalNavSettingsPanel',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'GNB Settings overlay — LNB with profile, search, sections (General, Theme, RFM, data, robotics, pipeline)',
    tags: ['settings', 'navigation', 'RFM', 'overlay'],
  },
  {
    id: 'rfm.listHeader',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'List title area with optional action',
    tags: ['header', 'list', 'cta'],
  },
  {
    id: 'rfm.robotSelectCard',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Flip-style robot option card for create-project robot picker',
    tags: ['project', 'create', 'robot', 'card'],
  },
  {
    id: 'rfm.sectionTitle',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Section sub-title with synchronized count chip',
    tags: ['title', 'section', 'count'],
  },
  {
    id: 'rfm.listSearchInput',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Search input for list screens',
    tags: ['search', 'list', 'input'],
  },
  {
    id: 'rfm.listFilterChips',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Filter chip group for quick list filtering',
    tags: ['filter', 'chips', 'list'],
  },
  {
    id: 'rfm.chip',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Chip size variants (filter md, tag xs, meta xs) for catalog-aligned composition',
    tags: ['chip', 'badge', 'token'],
  },
  {
    id: 'rfm.listSortSelect',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Sort dropdown for list screens',
    tags: ['sort', 'select', 'list'],
  },
  {
    id: 'rfm.formTagInput',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Enter-to-add tag chips with remove control for work page parameter forms',
    tags: ['form', 'tags', 'chips', 'input', 'workpage'],
  },
  {
    id: 'rfm.workPageFormField',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description:
      'Work page step-1 native form field — shared label typography for Register, Collect, and Generate flows',
    tags: ['form', 'label', 'workpage', 'RFM'],
  },
  {
    id: 'rfm.workPageFileUploadDropzone',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description:
      'Register work page file column — dashed dropzone, drag-and-drop, File Upload control; optional children slot (e.g. Text Prompt)',
    tags: ['form', 'file', 'upload', 'workpage', 'register'],
  },
  {
    id: 'rfm.activityStepContainer',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description:
      'Activity step card shell: header (title) + flex-1 scrollable content + optional footer — fills grid cell height without sticky/absolute',
    tags: ['workpage', 'layout', 'RFM', 'activity'],
  },
  {
    id: 'rfm.workPageActivityFooterToolbar',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description:
      'Footer action row for ActivityStepContainer — left secondary group + right primary (Collect teleop pattern); used only in card footer, not sticky',
    tags: ['workpage', 'toolbar', 'RFM', 'actions'],
  },
  {
    id: 'rfm.buttonCatalog',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Button variant token showcase aligned with buttonClasses',
    tags: ['button', 'tokens', 'catalog'],
  },
  {
    id: 'rfm.listStatusTabs',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Status tabs for list views',
    tags: ['tabs', 'status', 'list'],
  },
  {
    id: 'rfm.listState',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Empty/error/loading state component for lists',
    tags: ['state', 'empty', 'error'],
  },
  {
    id: 'rfm.overlayDialog',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Centered overlay dialog for global actions',
    tags: ['overlay', 'modal', 'dialog'],
  },
  {
    id: 'rfm.toast',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Transient bottom-right notification with optional auto-dismiss',
    tags: ['toast', 'notification', 'feedback'],
  },
  {
    id: 'rfm.editProfilePanel',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Edit Profile dialog body: name, avatar, project role badges, non-owner Dev role requests',
    tags: ['profile', 'overlay', 'roles', 'user'],
  },
  {
    id: 'rfm.screenDescriptionPanel',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Right-side description drawer panel for screen guidance',
    tags: ['overlay', 'drawer', 'description'],
  },
  {
    id: 'rfm.viewModeToggle',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Toggle between list and grid view modes',
    tags: ['view', 'toggle', 'list'],
  },
  {
    id: 'rfm.listToolbar',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Composed toolbar with search, chips, and sort',
    tags: ['toolbar', 'filter', 'list'],
  },
  {
    id: 'rfm.tablePagination',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Pagination control for tabular lists',
    tags: ['pagination', 'table', 'list'],
  },
  {
    id: 'rfm.projectCard',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Card item for project metadata',
    tags: ['card', 'project', 'list'],
  },
  {
    id: 'rfm.projectCardGrid',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Grid layout for project cards',
    tags: ['grid', 'project', 'layout'],
  },
  {
    id: 'rfm.libraryAssetCard',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Card item for library assets',
    tags: ['card', 'library', 'asset'],
  },
  {
    id: 'rfm.libraryAssetGrid',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Grid/list container for library asset cards',
    tags: ['grid', 'library', 'asset'],
  },
  {
    id: 'rfm.projectWorkspaceSidebar',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Left sidebar for project workspace navigation',
    tags: ['sidebar', 'project', 'navigation'],
  },
  {
    id: 'rfm.projectMetaInfoStrip',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Project meta information strip below title',
    tags: ['meta', 'project', 'header'],
  },
  {
    id: 'rfm.projectWorkspaceActivityCards',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Clickable activity entry cards; optional per-activity popover menu (e.g. Generate sub-modes)',
    tags: ['workspace', 'activity', 'entry', 'menu'],
  },
  {
    id: 'rfm.projectTaskList',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Assigned jobs list for project dashboard detail',
    tags: ['task', 'project', 'list'],
  },
  {
    id: 'rfm.projectInfoListPanel',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Generic compact info list panel for activity/member',
    tags: ['panel', 'list', 'project'],
  },
  {
    id: 'rfm.projectRobotInfoPanel',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Robot information summary panel',
    tags: ['robot', 'project', 'info'],
  },
  {
    id: 'rfm.projectOutputSummaryPanel',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Output summary metrics panel for datasets and models',
    tags: ['output', 'metric', 'project'],
  },
  {
    id: 'rfm.projectSelectorCard',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Selectable project card used in project switcher panel',
    tags: ['card', 'project', 'select'],
  },
  {
    id: 'rfm.projectSelectorPanel',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Centered modal project switcher with search and actions',
    tags: ['overlay', 'modal', 'project'],
  },
  {
    id: 'rfm.workspaceItemDetailDrawer',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Right-side detail drawer for workspace table item',
    tags: ['overlay', 'drawer', 'workspace'],
  },
  {
    id: 'rfm.projectJobsOnProcessDrawer',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Right-side jobs on process drawer for workspace',
    tags: ['overlay', 'drawer', 'workspace', 'jobs'],
  },
  {
    id: 'rfm.activityDraftHistoryDrawer',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Work page Load draft — unsaved activity draft sessions as cards (slide-in drawer)',
    tags: ['overlay', 'drawer', 'workspace', 'activity', 'draft'],
  },
  {
    id: 'rfm.workPageTemplateCanvas',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Template canvas block for work page type variants',
    tags: ['workpage', 'template', 'layout'],
  },
  {
    id: 'rfm.activityValidation',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description:
      'Shared Activity pre-processor step with summary cards, progress, results table; optional Skip to save dataset without running preprocessor',
    tags: ['workpage', 'pre-processor', 'activity', 'table'],
  },
  {
    id: 'rfm.activitySaveDataset',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description:
      'Activity step 3 — same shell/cards as steps 1–2 (rounded-xl, workPage canvas cards, two-column grid); export summary + save footer',
    tags: ['workpage', 'activity', 'save', 'dataset', 'RFM'],
  },
  {
    id: 'rfm.inviteMemberPanel',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Workspace Settings invite modal body — email/name search, user pick list, role select, send invite',
    tags: ['settings', 'members', 'invite', 'modal', 'role'],
  },
  {
    id: 'rfm.collectTeleoperationStep',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Collect activity step 1 — teleoperation parameters, episode and recording progress, camera tiles, session controls',
    tags: ['workpage', 'collector', 'teleoperation', 'RFM'],
  },
  {
    id: 'rfm.syntheticVideoCreationStep',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description:
      'Generate (synthetic video) step 1 — parameter form, Run/Save, progress and placeholder until complete, responsive video with playback and overflow actions',
    tags: ['workpage', 'generator', 'synthetic-video', 'RFM'],
  },
  {
    id: 'rfm.mimicAugmentationStep',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description:
      'Generate (mimic augmentation) step 1 — parameters + simulation file input, Run/Rerun, progress bar top of preview, large source thumbnail + grid of small augmented sim thumbnails',
    tags: ['workpage', 'generator', 'mimic-augmentation', 'RFM'],
  },
  {
    id: 'rfm.idmTrajectoryStep',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description:
      'Generate (IDM) step 1 — IDM model select, input video via file upload or dataset clip, Run fusion, trajectory overlay preview, continue to pre-processor',
    tags: ['workpage', 'generator', 'idm', 'inverse-dynamics', 'RFM'],
  },
  {
    id: 'rfm.mergeDatasetsStep',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description:
      'Curate (merge datasets) step 1 — multi-select saved workspace datasets via checkboxes, merged name/description, continue to pre-processor',
    tags: ['workpage', 'curator', 'merge-datasets', 'RFM'],
  },
  {
    id: 'rfm.curateAnalyticsStep',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Curate (analytics) step 1 — placeholder panel until analytics charts are specified',
    tags: ['workpage', 'curator', 'analytics', 'RFM'],
  },
  {
    id: 'rfm.workPageShell',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Full-size routed shell for work page with header and steps',
    tags: ['workpage', 'route', 'fullsize'],
  },
];
