export type BlockMeta = {
  id: string;
  version: string;
  owner: string;
  category: 'molecule' | 'organism';
  description: string;
  tags: string[];
};

export const blockRegistry: BlockMeta[] = [
  {
    id: 'rfm.filterBar',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Search and filter controls for list screens',
    tags: ['filter', 'search', 'list'],
  },
  {
    id: 'rfm.dataTable',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Tabular data display block',
    tags: ['table', 'list', 'columns'],
  },
  {
    id: 'rfm.globalTopNav',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Global navigation header',
    tags: ['navigation', 'global', 'header'],
  },
  {
    id: 'rfm.listHeader',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'List title area with optional action',
    tags: ['header', 'list', 'cta'],
  },
  {
    id: 'rfm.listSearchInput',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Search input for list screens',
    tags: ['search', 'list', 'input'],
  },
  {
    id: 'rfm.listFilterChips',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Filter chip group for quick list filtering',
    tags: ['filter', 'chips', 'list'],
  },
  {
    id: 'rfm.listSortSelect',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Sort dropdown for list screens',
    tags: ['sort', 'select', 'list'],
  },
  {
    id: 'rfm.listStatusTabs',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Status tabs for list views',
    tags: ['tabs', 'status', 'list'],
  },
  {
    id: 'rfm.listState',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Empty/error/loading state component for lists',
    tags: ['state', 'empty', 'error'],
  },
  {
    id: 'rfm.overlayDialog',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Centered overlay dialog for global actions',
    tags: ['overlay', 'modal', 'dialog'],
  },
  {
    id: 'rfm.screenDescriptionPanel',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Right-side description drawer panel for screen guidance',
    tags: ['overlay', 'drawer', 'description'],
  },
  {
    id: 'rfm.viewModeToggle',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Toggle between list and grid view modes',
    tags: ['view', 'toggle', 'list'],
  },
  {
    id: 'rfm.listToolbar',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Composed toolbar with search, chips, and sort',
    tags: ['toolbar', 'filter', 'list'],
  },
  {
    id: 'rfm.projectCard',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Card item for project metadata',
    tags: ['card', 'project', 'list'],
  },
  {
    id: 'rfm.projectCardGrid',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Grid layout for project cards',
    tags: ['grid', 'project', 'layout'],
  },
  {
    id: 'rfm.libraryAssetCard',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Card item for library assets',
    tags: ['card', 'library', 'asset'],
  },
  {
    id: 'rfm.libraryAssetGrid',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Grid/list container for library asset cards',
    tags: ['grid', 'library', 'asset'],
  },
  {
    id: 'rfm.projectWorkspaceSidebar',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Left sidebar for project workspace navigation',
    tags: ['sidebar', 'project', 'navigation'],
  },
  {
    id: 'rfm.projectMetaInfoStrip',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'molecule',
    description: 'Project meta information strip below title',
    tags: ['meta', 'project', 'header'],
  },
  {
    id: 'rfm.projectTaskList',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Assigned jobs list for project dashboard detail',
    tags: ['task', 'project', 'list'],
  },
  {
    id: 'rfm.projectInfoListPanel',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Generic compact info list panel for activity/member',
    tags: ['panel', 'list', 'project'],
  },
  {
    id: 'rfm.projectRobotInfoPanel',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Robot information summary panel',
    tags: ['robot', 'project', 'info'],
  },
  {
    id: 'rfm.projectOutputSummaryPanel',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Output summary metrics panel for datasets and models',
    tags: ['output', 'metric', 'project'],
  },
  {
    id: 'rfm.projectSelectorCard',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Selectable project card used in project switcher panel',
    tags: ['card', 'project', 'select'],
  },
  {
    id: 'rfm.projectSelectorPanel',
    version: '1.0.0',
    owner: 'product-design-system',
    category: 'organism',
    description: 'Centered modal project switcher with search and actions',
    tags: ['overlay', 'modal', 'project'],
  },
];
